apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ludi-ludi/Java-application-automation.git
    targetRevision: HEAD
    path: .
  destination: 
    server: https://kubernetes.default.svc
    namespace: java-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
